<?
$aMenuLinks = Array(
	Array(
		"Издания", 
		"/vyvod-khayl/?clear_cache=Y", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Рейтинги", 
		"/raiting/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Периодика", 
		"/periodika/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Сотруднику", 
		"/dolzhniki-sotr/", 
		Array(), 
		Array(), 
		"CBXFeatures::IsFeatureEnabled('crm') && CModule::IncludeModule('crm') && CCrmPerms::IsAccessEnabled()" 
	),
	Array(
		"Читателю", 
		"/poseshchaemost-cus/", 
		Array(), 
		Array(), 
		"CBXFeatures::IsFeatureEnabled('Workgroups')" 
	),
	Array(
		"Контакты", 
		"/index.html", 
		Array(), 
		Array(), 
		"" 
	)
);
?>